services:
  api:
    build: .
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--reload"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:${postgres_password}@db:5432/postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
