version: 2.1

jobs:
  build-and-test:
    docker:
      - image: tiangolo/uvicorn-gunicorn-fastapi:latest
        environment:
          postgres_password: ${POSTGRES_PASSWORD}
      - image: postgres:latest
        environment:
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t myapp:latest .
      - run:
          name: Start FastAPI app
          background: true
          command: docker run --network host myapp:latest
      - run:
          name: Wait for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Install Pytest
          command: pip install pytest
      - run:
          name: Run Pytest
          command: pytest

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
